Fixes before releasing
arviz-devs/arviz pull request #1495
Opened 2021-01-11 02:02 UTC by OriolAbril

## Description

## Checklist

- [x] Does the PR follow [official](https://github.com/arviz-devs/arviz/blob/master/CONTRIBUTING.md#pull-request-checklist) 
      PR format?
- [x] Is the code style correct (follows pylint and black guidelines)?
- [ ] Is the fix listed in the [Maintenance and fixes](https://github.com/arviz-devs/arviz/blob/master/CHANGELOG.md#maintenance-and-fixes) 
      section of the changelog?

2021-01-11 08:19 UTC, michaelosthege approved these changes

2021-01-11 14:12 UTC, michaelosthege commented
@OriolAbril FYI I can't merge this.

2021-01-11 15:35 UTC, rpgoldman requested changes
I suggested one minor tweak, but it looks good to me other than that.

2021-01-11 15:35 UTC, rpgoldman commented on arviz/data/io_pymc3.py
> +        density_dist_obs: Optional[bool] = True,
Shouldn't this be just `bool`, if the default is no longer going to be `None`?

2021-01-11 15:35 UTC, rpgoldman commented on arviz/data/io_pymc3.py
> +    density_dist_obs: Optional[bool] = True,
Same as above.

2021-01-12 01:11 UTC, canyon289 commented
Should there be tests, even if theyre not run in CI

2021-01-14 09:11 UTC, michaelosthege approved these changes
The changes look good. The CI failure looks unrelated to the changes from this PR

2021-01-15 08:56 UTC, michaelosthege commented
@OriolAbril can this be merged? The PR https://github.com/pymc-devs/pymc3/pull/4405 is blocked by the ArviZ release..

2021-01-15 09:07 UTC, AlexAndorra approved these changes

2021-01-15 13:11 UTC, merged