rename arviz-doc to arviz-docgrid and make arviz-doc a non-grid style
arviz-devs/arviz pull request #2157
Opened 2022-11-08 21:13 UTC by aloctavodia

2022-11-09 17:10 UTC, OriolAbril commented
cc @sarinac

2022-11-10 07:43 UTC, sarinac requested changes
Thanks @aloctavodia for adding! 

A few questions:
1. I made comments on keeping the doc/docgrid styles exactly the same except for `axes.grid=True`. LMK if any concerns.
2. Can you add the new `arviz-docgrid` to `doc/examples/matplotlib/mpl_styles.py`? That way users can discover it. 
3. This will remove grids for all charts generated throughout the entire documentation (homepage, example gallery, api documentation examples). Should we vary a few, change everything to `arviz-docgrid`, or leave things the way they are with the new `arviz-doc` (nothing will have grids)? My opinion is that there are some charts (e.g. violin) that look better with axes, but stuff like posterior plot (too cluttered in the examples right now) look better without.

2022-11-10 07:43 UTC, sarinac commented on arviz/plots/styles/arviz-doc.mplstyle
> -axes.grid.which:        major       # grid lines at {major, minor, both} ticks
Can we keep this? Without explicitly setting `axes.grid.which` to "major", the axis will show both major and minor. I like things more simple and less clutterry, which is what I was hoping this style goes for.

I think the only differentiator between `arviz-doc` and `arviz-docgrid` is the presence of the grid. Even with arviz-doc style applied, you can override the grid visibility by applying `plt.grid()`. If the user happens to do that, then I want it to match `arviz-docgrid`'s style to a tee.

2022-11-10 07:43 UTC, sarinac commented on arviz/plots/styles/arviz-doc.mplstyle
> -
Can we keep these too for the same reason above?

2022-11-10 13:16 UTC, aloctavodia commented
thanks for the comments @sarinac. I updated the styles

2022-11-11 02:22 UTC, sarinac approved these changes
🎉 🎉 🎉

2022-11-11 10:08 UTC, merged