WIP Update requirements.txt
arviz-devs/arviz pull request #2201
Opened 2023-02-03 17:35 UTC by canyon289

Testing to see what happens if we lower the matplotlib dependency. This is for google colab update

2023-02-03 18:36 UTC, canyon289 commented
ArviZ works on a lower version of matplotlib. To get google colab updated for both arviz and pymc I suggest we lower the minimum version to 3.2. Any issues if we do this and cut a release?

2023-02-04 18:49 UTC, canyon289 commented
Anyone know why we get pylint errors with no code changes?

2023-02-04 19:03 UTC, OriolAbril commented
New pylint version which is more strict I think

2023-02-04 19:04 UTC, OriolAbril requested changes

2023-02-04 19:04 UTC, OriolAbril commented on requirements.txt
> +matplotlib~=3.2
Remember to update this to >

2023-02-06 06:22 UTC, canyon289 commented on requirements.txt
> +matplotlib~=3.2
Thanks

2023-02-08 02:57 UTC, canyon289 commented
This is ready for rereview

2023-02-09 04:54 UTC, ahartikainen approved these changes

2023-02-09 04:56 UTC, merged